config/routes.rb
ProjectManager::Application.routes.draw do

  resources :projects

  resources :people

end

app/models/person.rb
class Person < ActiveRecord::Base
  
  validates :first_name, :presence => true
  validates :last_name,  :presence => true
  
  before_save :cleanup
  
  scope :all_lazy, select('*')
  scope :find_lazy, lambda {|id| where(primary_key => id) }
  scope :all_ordered_last, all_lazy.order("last_name ASC")
  
  def name
    "#{first_name} #{last_name}"
  end

  private
  
  def cleanup
    self[:first_name] = self[:first_name].capitalize
  end
  
end

app/models/project.rb
class Project < ActiveRecord::Base
	
	validates :title, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  before_filter :authenticate, :only => :show

  def index
    @people = [
        'luke-skywalker',
        'darth-vader'
      ]
  end
  
  def show
    @person = params[:id]
  end

  private
  
  def authenticate
    if params[:id] == "darth-vader"
      redirect_to people_url, :notice => "That page is restricted."
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def link_to_icon(icon_name, url_or_object, options={})
	options.merge! ({ :class => "icon #{icon_name}" })
		link_to(image_tag("icons/#{icon_name}.png"),
					url_or_object, options)
end

end

app/helpers/people_helper.rb
module PeopleHelper
	
	end

app/helpers/projects_helper.rb
module ProjectsHelper
def project_title_links(project)
	content_tag :h1 do
		[ project.title,
			link_to_icon('show', project_path(project)),
			link_to_icon('edit', edit_project_path(project)),
			link_to_icon('destroy', project, {
				:confirm => 'Are you sure?',
				:method => :delete
			})
		].join(' ')
	end
end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectManager</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  
<p id="notice"><%= notice %></p>

<%= yield %>

</body>
</html>

app/views/people/index.html.erb
<h1>People</h1>

<ul>
<% @people.each do |person| %>
    <li><%= link_to person, person_path(person) %></li>
<% end %>
</ul>

app/views/people/show.html.erb
<h1>Show template</h1>

<%= @person %>

<p><%= link_to "List of People", people_path %></p>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class="project">
<%= project_title_links(project) %>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<header>
<p>Projects</p>
</header>

<%= render @projects %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p>
  <b>Title:</b>
  <%= @project.title %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/shared/_includes.html.erb
	<%= stylesheet_link_tag 'scaffold', 'application' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>